using System.Collections;
using System.Collections.Generic;

using UnityEngine;
using UnityEngine.Rendering;
using Unity.Collections;

using System.Runtime.InteropServices;
using System;

/// <summary>
/// Managed bridge to one native volumetric-video decoder instance.
///
/// Unity owns the Mesh, Material, Texture2D objects, and AudioClip. The native
/// plugin decodes the combined MP4 and writes into registered graphics buffers
/// during GL.IssuePluginEvent. Audio is pulled through the streaming AudioClip
/// callback.
/// </summary>
public class VolumetricVideoDecoder
{
    //---------------------------------------------
    // DLL Interface
    //---------------------------------------------
    const string DLLNAME = "VolumetricVideoNativePlugin";

    // DLL Interfacece
    [DllImport(DLLNAME, EntryPoint = "GetRenderEventFunc")]
    private static extern IntPtr GetRenderEventFunc();

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_open_external_console")]
    private static extern void volumetricvideo_open_external_console();

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_close_external_console")]
    private static extern void volumetricvideo_close_external_console();

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_init")]
    private static extern int volumetricvideo_init(ref int ID);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_quit")]
    private static extern void volumetricvideo_quit(int ID);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_set_time")]
    private static extern void volumetricvideo_set_time(int ID, double time);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_start_decoding")]
    private static extern int volumetricvideo_start_decoding(int ID);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_stop_decoding")]
    private static extern int volumetricvideo_stop_decoding(int ID);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_seek")]
    private static extern int volumetricvideo_seek(int ID, double time);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_load_video")]
    private static extern int volumetricvideo_load_video(int ID, string filename);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_get_last_error")]
    private static extern IntPtr volumetricvideo_get_last_error(int ID);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_get_video_details")]
    private static extern int volumetricvideo_get_video_details(int ID, ref int width, ref int height, ref double fps, ref double duration);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_get_audio_details")]
    private static extern int volumetricvideo_get_audio_details(int ID, ref int sample_rate, ref int channels);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_read_audio")]
    private static extern int volumetricvideo_read_audio(int ID, [Out] float[] samples, int sample_count);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_get_texture_pointers")]
    private static extern int volumetricvideo_get_texture_pointers(int ID, ref IntPtr Y, ref IntPtr U, ref IntPtr V);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_set_mesh_pointer")]
    private static extern int volumetricvideo_set_mesh_pointer(int ID, IntPtr index_buffer_handle, int index_size, IntPtr vertex_buffer_handle, int vertex_size);

    //---------------------------------------------
    // Member variables
    //---------------------------------------------

    // Instance ID generated by plugin
    private int m_instance_id = -1;

    // Width and height of video - returned by plugin
    private int video_width = -1, video_height = -1;

    // Video FPS and duration returned by plugin
    private double video_fps = 0.0, video_duration = 0.0;

    // Textures - resources generated by Plugin and then constructed with unity in init_textures funciton
    private Texture2D m_YTexture, m_UTexture, m_VTexture;

    private AudioClip m_audio_clip;
    public AudioClip AudioClip
    {
        get { return m_audio_clip; }
    }

    public bool HasAudio
    {
        get { return m_audio_clip != null; }
    }

    // Mesh Filter - the form of the object
    private Mesh m_mesh;
    public Mesh Mesh
    {
        get{return m_mesh;}
    }

    // Mesh Renderer - the way the object looks on screen
    private MeshRenderer m_mesh_renderer;
    public MeshRenderer MeshRenderer
    {
        get {return m_mesh_renderer;}
    }


    // keeps track of last frame index that has been displayed
    private int m_previous_frame;

    // Flag for debug mode
    private bool m_debug;

    // Enum for decodered state
    public enum DecoderState
    {
        INIT_FAIL = -1,
        UNINITIALIZED,
        INITIALIZED,
        STARTED,
        STOPPED,
    };

    // 
    private DecoderState m_decoder_state = DecoderState.UNINITIALIZED;
    public DecoderState DecoderStatus
    {
        get{return m_decoder_state; }
        set { m_decoder_state = value; }
    }

    // Flag to detect a loop has occured
    private bool m_loop = false;
    public bool ContentLooped
    {
        get { return m_loop; }
    }

    //---------------------------------------------
    // Constructor
    //---------------------------------------------
    public VolumetricVideoDecoder(bool debug)
    {
        // Set state to uninitialised 
        m_decoder_state = DecoderState.UNINITIALIZED;

        // Set up debug console
        m_debug = debug;
        if (m_debug)
        {
            Debug.Log("VolumetricVideoDecoder - Opening External Console");
            volumetricvideo_open_external_console();
        }

        // Init Instance of Volumetric Video decoder
        if (volumetricvideo_init(ref m_instance_id) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init - failed to init");
            m_decoder_state = DecoderState.INIT_FAIL;
        }
        Debug.Log(String.Format("VolumetricVideoDecoder::init - instance ID: {0}", m_instance_id));

        // decoder init
        m_decoder_state = DecoderState.INITIALIZED;
    }

    //---------------------------------------------
    // Destructor
    //---------------------------------------------
    ~VolumetricVideoDecoder()
    {
        // Release Textures
        m_YTexture = null;
        m_UTexture = null;
        m_VTexture = null;
        m_audio_clip = null;
        
        // Close logging terminal
        if(m_debug)
        {
            Debug.Log(String.Format("VolumetricVideoDecoder::~VolumetricVideoDecoder - Closing External Console - id: {0}", m_instance_id));
            volumetricvideo_close_external_console();
        }

        // quit decoder plugin
        Debug.Log(String.Format("VolumetricVideoDecoder::~VolumetricVideoDecoder - Destructor - id: {0}", m_instance_id));
        volumetricvideo_quit(m_instance_id);
    }


    //----------------------------------------------------------
    // Vertex Data structure
    //----------------------------------------------------------
    [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]
    struct Vertex
    {
        public Vertex(float x, float y, float z, float nx, float ny, float nz, float u, float v)
        {
            pos     = new Vector3(x, y, z);
            normal  = new Vector3(nx, ny, nz);
            uv      = new Vector3(u, v);
        }
        public Vector3 pos;
        public Vector3 normal;
        public Vector2 uv;
    }

    //----------------------------------------------------------
    // Start the decoder
    //----------------------------------------------------------
    public bool init_mesh()
    {
        // Check for init
        if (m_decoder_state != DecoderState.INITIALIZED)
        {
            Debug.LogError("VolumetricVideoDecoder::init_mesh - failed to init");
            return false;
        }

        // Create New Mesh
        m_mesh = new Mesh();

        // Mark mesh as dynamic so it is writable and accessiable on the CPU
        m_mesh.MarkDynamic();

        // Vertex Count 
        const int vertex_count = 65535 ;
        const int index_count = 3 * 100000;

         // allocated vertex buffer and buffer layout 
        var layout = new[]
        {
            new VertexAttributeDescriptor(VertexAttribute.Position,     VertexAttributeFormat.Float32, 3),
            new VertexAttributeDescriptor(VertexAttribute.Normal,       VertexAttributeFormat.Float32, 3),
            new VertexAttributeDescriptor(VertexAttribute.TexCoord0,    VertexAttributeFormat.Float32, 2)
        };
        m_mesh.SetVertexBufferParams(vertex_count, layout);

        // init buffer with zeros - not sure if this is necessary
        NativeArray<Vertex> vert_buffer_data = new NativeArray<Vertex>(vertex_count, Allocator.Temp);
        for (int i = 0; i < vertex_count; i++)
        {
            vert_buffer_data[i] = new Vertex(0, 0, 0, 0, 0, 0, 0, 0);
        }
        m_mesh.SetVertexBufferData(vert_buffer_data, 0, 0, vertex_count);
        vert_buffer_data.Dispose();

        // Init indexes that make up the triangles
        int[] tris_array = new int[index_count];
        for (int i = 0; i < index_count; i++)
        {
            tris_array[i] = 0;
        }

        //
        m_mesh.indexFormat    = UnityEngine.Rendering.IndexFormat.UInt32;
        m_mesh.triangles      = tris_array;

        // Get Buffer Handles
        IntPtr index_buffer     = m_mesh.GetNativeIndexBufferPtr();
        IntPtr vertex_buffer    = m_mesh.GetNativeVertexBufferPtr(0);

        Debug.Log(String.Format("VolumetricVideoDecoder::init_mesh - {0} {1}", index_buffer, vertex_buffer));

        // Pass handles to Native Plugin
        if (volumetricvideo_set_mesh_pointer(m_instance_id, index_buffer, index_count, vertex_buffer, vertex_count ) == -1)
        {
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        //
        Debug.Log("VolumetricVideoDecoder::init_mesh - Done");
        return true;
    }


    //---------------------------------------------
    // Function to init the volumetric video decoder
    // Requires a reference to the MeshRenderer from the parent class
    //---------------------------------------------
    public bool init_texture(ref  MeshRenderer mesh_renderer, string video_file)
    {
        //
        m_mesh_renderer = mesh_renderer;

        // Check for init
        if (m_decoder_state != DecoderState.INITIALIZED)
        {
            Debug.LogError("VolumetricVideoDecoder::init_texture - failed to init");
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        // Load Video
        if(!load_video(video_file, ref video_width, ref video_height, ref video_fps, ref video_duration))
        {
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }   

        // Create Texture Resources         
        if(!init_textures(ref  m_mesh_renderer, video_width, video_height))
        {
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }
         
        // Seek to start of file
        volumetricvideo_seek(m_instance_id, 0.0);
        
        //
        return true;
    }


    //---------------------------------------------
    // Load video and return important properties
    //---------------------------------------------
    private bool load_video(string filepath,  ref int video_width, ref int video_height, ref double video_fps, ref double video_duration )
    {
        // Load Video
        if (volumetricvideo_load_video(m_instance_id, filepath) == -1)
        {
            IntPtr errorPointer = volumetricvideo_get_last_error(m_instance_id);
            string detail = errorPointer == IntPtr.Zero
                ? String.Empty
                : Marshal.PtrToStringAnsi(errorPointer);
            Debug.LogError("VolumetricVideoDecoder::init - failed to load video"
                + (String.IsNullOrEmpty(detail) ? String.Empty : ": " + detail));
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        // Get Video Details
        if(volumetricvideo_get_video_details(m_instance_id,  ref video_width, ref video_height, ref video_fps, ref video_duration) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init - failed to get video details");
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        // Log some details
        Debug.Log( String.Format("VolumetricVideoDecoder::init - file:  {0}", filepath));
        Debug.Log( String.Format("VolumetricVideoDecoder::init - width: {0}  height:   {1}",video_width, video_height));
        Debug.Log( String.Format("VolumetricVideoDecoder::init - fps:   {0}  duration: {1}",video_fps, video_duration));

        //
        return true;
    }

    public bool init_audio()
    {
        int sampleRate = 0;
        int channels = 0;
        int result = volumetricvideo_get_audio_details(
            m_instance_id, ref sampleRate, ref channels);
        if (result == 0)
        {
            Debug.Log("VolumetricVideoDecoder::init_audio - no audio stream");
            return true;
        }
        if (result < 0 || sampleRate <= 0 || channels <= 0)
        {
            Debug.LogError("VolumetricVideoDecoder::init_audio - invalid audio stream");
            return false;
        }

        int lengthSamples = Math.Max(
            1, (int)Math.Ceiling(video_duration * sampleRate));
        m_audio_clip = AudioClip.Create(
            "VolumetricVideoAudio",
            lengthSamples,
            channels,
            sampleRate,
            true,
            read_audio);
        Debug.Log(String.Format(
            "VolumetricVideoDecoder::init_audio - {0} Hz, {1} channels",
            sampleRate, channels));
        return m_audio_clip != null;
    }

    private void read_audio(float[] samples)
    {
        int read = volumetricvideo_read_audio(
            m_instance_id, samples, samples.Length);
        if (read < 0)
        {
            Array.Clear(samples, 0, samples.Length);
        }
    }


    //---------------------------------------------
    // Function to create texture pointers which are then created by the native plugin
    //---------------------------------------------
    private bool init_textures(ref  MeshRenderer mesh_renderer, int width, int height)
    {
        // Find shader
        try
        {
            mesh_renderer.material = new Material(Shader.Find("VolumetricVideo/YUV2RGBA"));
        }
        catch
        {
            Debug.LogError("VolumetricVideoDecoder::init_textures - YUV2RGBA shader not found");
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        // Create textures 
        IntPtr Y = new IntPtr();
        IntPtr U = new IntPtr();
        IntPtr V = new IntPtr();
    
        // Get/Set texture pointers
        if(volumetricvideo_get_texture_pointers(m_instance_id, ref Y, ref U, ref V) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init_textures - Error Creating Textures");
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        // Create Unity Textures - Y is full size - U & V are half size
        m_YTexture = Texture2D.CreateExternalTexture(width,     height,     TextureFormat.Alpha8, false, false, Y);
        m_UTexture = Texture2D.CreateExternalTexture(width/2,   height/2,   TextureFormat.Alpha8, false, false, U);
        m_VTexture = Texture2D.CreateExternalTexture(width/2,   height/2,   TextureFormat.Alpha8, false, false, V);

        // Set Shader Uniforms
        mesh_renderer.material.SetTexture("_YTex", m_YTexture);
        mesh_renderer.material.SetTexture("_UTex", m_UTexture);
        mesh_renderer.material.SetTexture("_VTex", m_VTexture);

        //
        return true;
    }


    //----------------------------------------------------------
    // Start the decoder
    //----------------------------------------------------------
    public bool start_decoding()
    {
        // Check decoder has started before attempting to stop
        if (m_decoder_state != DecoderState.INITIALIZED)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::start - Failed to start decoder for instance {0} - decoder not initialised", m_instance_id));
            return false;
        }

        // Start Decoder
        if (volumetricvideo_start_decoding(m_instance_id) == -1)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::start - Failed to start decoder for instance {0}",m_instance_id) );
            return false;
        }

        // Update internal state
        m_decoder_state = DecoderState.STARTED;

        //
        return true;
    }

    //----------------------------------------------------------
    // Stop the decoder
    //----------------------------------------------------------
    public bool stop_decoding()
    {
        // If decoder has stopped - then nothing to do
        if(m_decoder_state == DecoderState.STOPPED)
        {    
            return false;
        }

        // Check decoder has started before attempting to stop
        if(m_decoder_state != DecoderState.STARTED)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::stop - Failed to stop decoder for instance {0} - Decoder status has not started", m_instance_id));
            return false;
        }

        //
        if(volumetricvideo_stop_decoding(m_instance_id) == -1)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::stop - Failed to start decoder for instance {0}",m_instance_id) );
            return false;
        }

        //
        m_decoder_state = DecoderState.STOPPED;

        //
        return true;
    }


    //----------------------------------------------------------
    // Function to set the frame counter - this should be a time within the volumetric sequence e.g. 5 secs
    // This is then normalised within the sequence
    //----------------------------------------------------------
    public void update(double time)
    {
        double presentation_time = time % video_duration;

        // Compute frame within the sequence
        int current_frame = (int)(presentation_time * video_fps);

        //Check if there is a requirement to update the frame
        if (m_previous_frame != current_frame)
        {
            // The managed playback clock owns loop detection. Reset every
            // native stream before requesting frame zero so no texture,
            // geometry, or audio from the previous pass can leak across.
            if(current_frame < m_previous_frame)
            {
                m_loop = true;
                if(volumetricvideo_seek(m_instance_id, 0.0) == -1)
                {
                    Debug.LogError("VolumetricVideoDecoder::update - failed to reset decoder at loop boundary");
                    return;
                }
            }

            // Video, geometry, and audio all use the same DSP-clock time.
            volumetricvideo_set_time(m_instance_id, presentation_time);

            // Issue render event
            GL.IssuePluginEvent(GetRenderEventFunc(), m_instance_id);

            // Recalculate Mesh Bounds
            m_mesh.RecalculateBounds();
            
            // keep track of previous frame
            m_previous_frame = current_frame;
        }    
    }

    //----------------------------------------------------------
    //
    //----------------------------------------------------------
    public void set_colour_correction_values(float luminaceCorrection, float blueProjectionCorrection, float redProjectionCorrection)
    {
        if(m_decoder_state >= DecoderState.INITIALIZED)
        {
             m_mesh_renderer.material.SetFloat("_LuminanceCorrection", luminaceCorrection);
             m_mesh_renderer.material.SetFloat("_BlueProjectionCorrection", blueProjectionCorrection);
             m_mesh_renderer.material.SetFloat("_RedProjectionCorrection", redProjectionCorrection);
        }
    }


}
