using System.Collections;
using System.Collections.Generic;

using UnityEngine;
using UnityEngine.Rendering;
using Unity.Collections;

using System.Runtime.InteropServices;
using System;

public class VolumetricVideoDecoder 
{
    // --------------------------------------
    // DLL Name
    const string DLLNAME = "VolumetricVideoNativePlugin3";

    // DLL Interfacec 
    [DllImport(DLLNAME, EntryPoint = "GetRenderEventFunc")]
    private static extern IntPtr GetRenderEventFunc();

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_open_external_console")]
    private static extern void volumetricvideo_open_external_console();

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_close_external_console")]
    private static extern void volumetricvideo_close_external_console();

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_init")]
    private static extern int volumetricvideo_init(ref int ID);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_quit")]
    private static extern void volumetricvideo_quit(int ID);
    
    [DllImport(DLLNAME, EntryPoint="volumetricvideo_start_decoding")]
    private static extern int volumetricvideo_start_decoding(int ID);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_stop_decoding")]
    private static extern int volumetricvideo_stop_decoding(int ID);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_update")]
    private static extern int volumetricvideo_update(int ID);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_seek")]
    private static extern int volumetricvideo_seek(int ID, double time);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_load_video")]
    private static extern int volumetricvideo_load_video(int ID, string filename);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_get_video_details")]
    private static extern int volumetricvideo_get_video_details(int ID, ref int width, ref int height, ref double fps, ref double duration);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_get_texture_pointers")]
    private static extern int volumetricvideo_get_texture_pointers(int ID, ref IntPtr Y, ref IntPtr U, ref IntPtr V);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_set_mesh_pointer")]
    private static extern int volumetricvideo_set_mesh_pointer(int ID, IntPtr index_buffer_handle, int index_size, IntPtr vertex_buffer_handle, int vertex_size);


    // --------------------------------------
    // Member variables
    //

    // Instance ID generated by plugin
    private int m_instance_id = -1;
    
    // Width and height of video - returned by plugin
    private int video_width=-1, video_height=-1;

    // Video FPS and duration returned by plugin
    private double video_fps =0.0, video_duration=0.0;

    // Textures - resources generated by Plugin and then constructed with unity in init_textures funciton
    private Texture2D m_YTexture, m_UTexture, m_VTexture;

    // keeps track of last frame index that has been displayed
    private int m_previous_frame;

    // Flag for debug mode
    private bool m_debug;

    // Flag to determine if decoder has been init'ed
    private bool m_init;

    //---------------------------------------
    // Constructor
    //
    public VolumetricVideoDecoder(bool debug )
    {
        // Set up debug console
        m_debug = debug;
        if (m_debug)
        {
            Debug.Log("VolumetricVideoDecoder - Opening External Console");
            volumetricvideo_open_external_console();
        }

        // Init Instance of Volumetric Video decoder
        if (volumetricvideo_init(ref m_instance_id) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init - failed to init");
            m_init = false;
        }
        Debug.Log(String.Format("VolumetricVideoDecoder::init - instance ID: {0}", m_instance_id));

        // decoder init
        m_init = true;
    }

    //---------------------------------------
    // Destructor
    //
    ~VolumetricVideoDecoder()
    {
        // Release Textures
        m_YTexture = null;
        m_UTexture = null;
        m_VTexture = null;
        
        // Close logging terminal
        if(m_debug)
        {
            Debug.Log(String.Format("VolumetricVideoDecoder::~VolumetricVideoDecoder - Closing External Console - id: {0}", m_instance_id));
            volumetricvideo_close_external_console();
        }

        // quit decoder plugin
        Debug.Log(String.Format("VolumetricVideoDecoder::~VolumetricVideoDecoder - Destructor - id: {0}", m_instance_id));
        volumetricvideo_quit(m_instance_id);
    }


    //------------------------------------------
    // Function to init the volumetric video decoder
    // Requires a reference to the MeshRenderer from the parent class
    //
    public bool init_texture(ref  MeshRenderer mesh_renderer, string video_file)
    {
        // Check for init
        if(!m_init)
        {
            Debug.LogError("VolumetricVideoDecoder::init_texture - failed to init");
            return false;
        }

        // Load Video
        if(!load_video(video_file, ref video_width, ref video_height, ref video_fps, ref video_duration))
        {
             return false;
        }   

        // Create Texture Resources         
        if(!init_textures(ref  mesh_renderer, video_width, video_height))
        {
            return false;
        }
         
        // Seek to start of file
        volumetricvideo_seek(m_instance_id, 0.0);
        
        //
        return true;
    }


    //------------------------------
    // Load video and return important properties
    //
    private bool load_video(string filepath,  ref int video_width, ref int video_height, ref double video_fps, ref double video_duration )
    {
        // Load Video
        if (volumetricvideo_load_video(m_instance_id, filepath) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init - failed to load video");
            return false;
        }

        // Get Video Details
        if(volumetricvideo_get_video_details(m_instance_id,  ref video_width, ref video_height, ref video_fps, ref video_duration) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init - failed to get video details");
            return false;
        }

        // Log some details
        Debug.Log( String.Format("VolumetricVideoDecoder::init - file:  {0}", filepath));
        Debug.Log( String.Format("VolumetricVideoDecoder::init - width: {0}  height:   {1}",video_width, video_height));
        Debug.Log( String.Format("VolumetricVideoDecoder::init - fps:   {0}  duration: {1}",video_fps, video_duration));

        //
        return true;
    }


    //---------------------------------------------
    // Function to create texture pointers which are then created by the native plugin
    //
    private bool init_textures(ref  MeshRenderer mesh_renderer, int width, int height)
    {
        // Find shader
        try
        {
            mesh_renderer.material = new Material(Shader.Find("VolumetricVideo/YUV2RGBA"));
        }
        catch
        {
            Debug.LogError("VolumetricVideoDecoder::init_textures - YUV2RGBA shader not found");
            return false;
        }

        // Create textures 
        IntPtr Y = new IntPtr();
        IntPtr U = new IntPtr();
        IntPtr V = new IntPtr();
    
        // Get/Set texture pointers
        if(volumetricvideo_get_texture_pointers(m_instance_id, ref Y, ref U, ref V) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init_textures - Error Creating Textures"); 
            return false;
        }

        // Create Unity Textures - Y is full size - U & V are half size
        m_YTexture = Texture2D.CreateExternalTexture(width,     height,     TextureFormat.Alpha8, false, false, Y);
        m_UTexture = Texture2D.CreateExternalTexture(width/2,   height/2,   TextureFormat.Alpha8, false, false, U);
        m_VTexture = Texture2D.CreateExternalTexture(width/2,   height/2,   TextureFormat.Alpha8, false, false, V);

        // Set Shader Uniforms
        mesh_renderer.material.SetTexture("_YTex", m_YTexture);
        mesh_renderer.material.SetTexture("_UTex", m_UTexture);
        mesh_renderer.material.SetTexture("_VTex", m_VTexture);

        //
        return true;
    }

    [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]
    struct Vertex
    {
        public Vertex(float x, float y, float z, float nx, float ny, float nz, float u, float v)
        {
            pos     = new Vector3(x, y, z);
            normal  = new Vector3(nx, ny, nz);
            uv      = new Vector3(u, v);
        }
        public Vector3 pos;
        public Vector3 normal;
        public Vector2 uv;
    }

    //----------------------------------------------------------
    // Start the decoder
    //
    public bool init_mesh(ref Mesh mesh)
    {
        // Check for init
        if (!m_init)
        {
            Debug.LogError("VolumetricVideoDecoder::init_texture - failed to init");
            return false;
        }

        // Vertex Count 
        const int vertex_count      = 65535;
        const int triangle_count    = 2;

        // specify vertex count and layout
        var layout = new[]
        {
            new VertexAttributeDescriptor(VertexAttribute.Position,     VertexAttributeFormat.Float32, 3),
            new VertexAttributeDescriptor(VertexAttribute.Normal,       VertexAttributeFormat.Float32, 3),
            new VertexAttributeDescriptor(VertexAttribute.TexCoord0,    VertexAttributeFormat.Float32, 2)
        };
        mesh.SetVertexBufferParams(vertex_count, layout);

        //
        NativeArray<Vertex> vert_buffer_data = new NativeArray<Vertex>(vertex_count, Allocator.Temp);
        for (int i = 0; i < vertex_count; i++)
        {
            vert_buffer_data[i] = new Vertex(0, 0, 0, 0, 0, 0, 0, 0);
        }

        mesh.SetVertexBufferData(vert_buffer_data, 0, 0, vertex_count);

    //
        int[] tris_array = new int[6]
        {
            // lower left triangle
            0, 2, 1,
            // upper right triangle
            2, 3, 1
        };
        mesh.triangles = tris_array;

          
        // Mark mesh as dynamic so that it gets updated
        mesh.MarkDynamic();

        // Get Buffer Handles
        IntPtr index_buffer     = mesh.GetNativeIndexBufferPtr();
        IntPtr vertex_buffer    = mesh.GetNativeVertexBufferPtr(0);

        // Pass handles to Native Plugin
        if (volumetricvideo_set_mesh_pointer(m_instance_id, index_buffer, triangle_count*3, vertex_buffer, vertex_count ) == -1)
        {
            return false;
        }

        //
        Debug.Log("VolumetricVideoDecoder::init_texture - Done");
        return true;
    }


    //----------------------------------------------------------
    // Start the decoder
    //
    public bool start_decoding()
    {
        //
        if(volumetricvideo_start_decoding(m_instance_id) == -1)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::start - Failed to start decoder for instance {0}",m_instance_id) );
            return false;
        }

        //
        return true;
    }

    //----------------------------------------------------------
    // Start the decoder
    //
    public bool stop_decoding()
    {
        //
        if(volumetricvideo_stop_decoding(m_instance_id) == -1)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::start - Failed to start decoder for instance {0}",m_instance_id) );
            return false;
        }

        //
        return true;
    }


    //----------------------------------------------------------
    // Function to set the frame counter - this should be a time within the volumetric sequence e.g. 5 secs
    // This is then normalised within the sequence
    //
    public void update(double time)
    {
        // Compute frame within the sequence
        int current_frame = (int)( (time * video_fps) % (video_fps*video_duration) );

        //Check if there is a requirement to update the frame
        if (m_previous_frame != current_frame)
        {
            //
            GL.IssuePluginEvent(GetRenderEventFunc(), m_instance_id);

            //
            m_previous_frame = current_frame;
        }    
    }

}
