using System.Collections;
using System.Collections.Generic;

using UnityEngine;
using UnityEngine.Rendering;
using Unity.Collections;

using System.Runtime.InteropServices;
using System;

//---------------------------------------------
// 
//---------------------------------------------

public class VolumetricVideoDecoder 
{
    //---------------------------------------------
    // DLL Interface
    //---------------------------------------------
    const string DLLNAME = "VolumetricVideoNativePlugin";

    // DLL Interfacece
    [DllImport(DLLNAME, EntryPoint = "GetRenderEventFunc")]
    private static extern IntPtr GetRenderEventFunc();

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_open_external_console")]
    private static extern void volumetricvideo_open_external_console();

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_close_external_console")]
    private static extern void volumetricvideo_close_external_console();

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_init")]
    private static extern int volumetricvideo_init(ref int ID);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_quit")]
    private static extern void volumetricvideo_quit(int ID);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_set_unity_time")]
    private static extern void volumetricvideo_set_unity_time(int ID, double unity_time);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_set_frame")]
    private static extern void volumetricvideo_set_frame(int ID, int frame_index);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_start_decoding")]
    private static extern int volumetricvideo_start_decoding(int ID);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_stop_decoding")]
    private static extern int volumetricvideo_stop_decoding(int ID);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_update")]
    private static extern int volumetricvideo_update(int ID);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_seek")]
    private static extern int volumetricvideo_seek(int ID, double time);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_load_video")]
    private static extern int volumetricvideo_load_video(int ID, string filename);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_get_video_details")]
    private static extern int volumetricvideo_get_video_details(int ID, ref int width, ref int height, ref double fps, ref double duration);

    [DllImport(DLLNAME, EntryPoint="volumetricvideo_get_texture_pointers")]
    private static extern int volumetricvideo_get_texture_pointers(int ID, ref IntPtr Y, ref IntPtr U, ref IntPtr V);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_set_mesh_pointer")]
    private static extern int volumetricvideo_set_mesh_pointer(int ID, IntPtr index_buffer_handle, int index_size, IntPtr vertex_buffer_handle, int vertex_size);

    [DllImport(DLLNAME, EntryPoint = "volumetricvideo_load_mesh_data")]
    private static extern int	volumetricvideo_load_mesh_data(int ID, string filepattern, int start_frame, int end_frame);

    //---------------------------------------------
    // Member variables
    //---------------------------------------------

    // Instance ID generated by plugin
    private int m_instance_id = -1;
    
    // Width and height of video - returned by plugin
    private int video_width=-1, video_height=-1;

    // Video FPS and duration returned by plugin
    private double video_fps =0.0, video_duration=0.0;

    // Textures - resources generated by Plugin and then constructed with unity in init_textures funciton
    private Texture2D m_YTexture, m_UTexture, m_VTexture;

    // keeps track of last frame index that has been displayed
    private int m_previous_frame;

    // Flag for debug mode
    private bool m_debug;

    // Flag to determine if decoder has been init'ed
    private bool m_init;

    //---------------------------------------------
    // Constructor
    //---------------------------------------------
    public VolumetricVideoDecoder(bool debug )
    {
        // Set up debug console
        m_debug = debug;
        if (m_debug)
        {
            Debug.Log("VolumetricVideoDecoder - Opening External Console");
            volumetricvideo_open_external_console();
        }

        // Init Instance of Volumetric Video decoder
        if (volumetricvideo_init(ref m_instance_id) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init - failed to init");
            m_init = false;
        }
        Debug.Log(String.Format("VolumetricVideoDecoder::init - instance ID: {0}", m_instance_id));

        // decoder init
        m_init = true;
    }

    //---------------------------------------------
    // Destructor
    //---------------------------------------------
    ~VolumetricVideoDecoder()
    {
        // Release Textures
        m_YTexture = null;
        m_UTexture = null;
        m_VTexture = null;
        
        // Close logging terminal
        if(m_debug)
        {
            Debug.Log(String.Format("VolumetricVideoDecoder::~VolumetricVideoDecoder - Closing External Console - id: {0}", m_instance_id));
            volumetricvideo_close_external_console();
        }

        // quit decoder plugin
        Debug.Log(String.Format("VolumetricVideoDecoder::~VolumetricVideoDecoder - Destructor - id: {0}", m_instance_id));
        volumetricvideo_quit(m_instance_id);
    }


    //---------------------------------------------
    // Function to init the volumetric video decoder
    // Requires a reference to the MeshRenderer from the parent class
    //---------------------------------------------
    public bool init_texture(ref  MeshRenderer mesh_renderer, string video_file)
    {
        // Check for init
        if(!m_init)
        {
            Debug.LogError("VolumetricVideoDecoder::init_texture - failed to init");
            return false;
        }

        // Load Video
        if(!load_video(video_file, ref video_width, ref video_height, ref video_fps, ref video_duration))
        {
             return false;
        }   

        // Create Texture Resources         
        if(!init_textures(ref  mesh_renderer, video_width, video_height))
        {
            return false;
        }
         
        // Seek to start of file
        volumetricvideo_seek(m_instance_id, 0.0);
        
        //
        return true;
    }


    //---------------------------------------------
    // Load video and return important properties
    //---------------------------------------------
    private bool load_video(string filepath,  ref int video_width, ref int video_height, ref double video_fps, ref double video_duration )
    {
        // Load Video
        if (volumetricvideo_load_video(m_instance_id, filepath) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init - failed to load video");
            return false;
        }

        // Get Video Details
        if(volumetricvideo_get_video_details(m_instance_id,  ref video_width, ref video_height, ref video_fps, ref video_duration) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init - failed to get video details");
            return false;
        }

        // Log some details
        Debug.Log( String.Format("VolumetricVideoDecoder::init - file:  {0}", filepath));
        Debug.Log( String.Format("VolumetricVideoDecoder::init - width: {0}  height:   {1}",video_width, video_height));
        Debug.Log( String.Format("VolumetricVideoDecoder::init - fps:   {0}  duration: {1}",video_fps, video_duration));

        //
        return true;
    }


    //---------------------------------------------
    // Function to create texture pointers which are then created by the native plugin
    //---------------------------------------------
    private bool init_textures(ref  MeshRenderer mesh_renderer, int width, int height)
    {
        // Find shader
        try
        {
            mesh_renderer.material = new Material(Shader.Find("VolumetricVideo/YUV2RGBA"));
        }
        catch
        {
            Debug.LogError("VolumetricVideoDecoder::init_textures - YUV2RGBA shader not found");
            return false;
        }

        // Create textures 
        IntPtr Y = new IntPtr();
        IntPtr U = new IntPtr();
        IntPtr V = new IntPtr();
    
        // Get/Set texture pointers
        if(volumetricvideo_get_texture_pointers(m_instance_id, ref Y, ref U, ref V) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init_textures - Error Creating Textures"); 
            return false;
        }

        // Create Unity Textures - Y is full size - U & V are half size
        m_YTexture = Texture2D.CreateExternalTexture(width,     height,     TextureFormat.Alpha8, false, false, Y);
        m_UTexture = Texture2D.CreateExternalTexture(width/2,   height/2,   TextureFormat.Alpha8, false, false, U);
        m_VTexture = Texture2D.CreateExternalTexture(width/2,   height/2,   TextureFormat.Alpha8, false, false, V);

        // Set Shader Uniforms
        mesh_renderer.material.SetTexture("_YTex", m_YTexture);
        mesh_renderer.material.SetTexture("_UTex", m_UTexture);
        mesh_renderer.material.SetTexture("_VTex", m_VTexture);

        //
        return true;
    }

    //----------------------------------------------------------
    // Vertex Data structure
    //----------------------------------------------------------
    [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]
    struct Vertex
    {
        public Vertex(float x, float y, float z, float nx, float ny, float nz, float u, float v)
        {
            pos     = new Vector3(x, y, z);
            normal  = new Vector3(nx, ny, nz);
            uv      = new Vector3(u, v);
        }
        public Vector3 pos;
        public Vector3 normal;
        public Vector2 uv;
    }

    //----------------------------------------------------------
    // Start the decoder
    //----------------------------------------------------------
    public bool init_mesh(ref Mesh mesh)
    {
        // Check for init
        if (!m_init)
        {
            Debug.LogError("VolumetricVideoDecoder::init_mesh - failed to init");
            return false;
        }

        // Mark mesh as dynamic so it is writable and accessiable on the CPU
        mesh.MarkDynamic();

        // Vertex Count 
        const int vertex_count = 65535 ;
        const int index_count = 3 * 100000;

         // allocated vertex buffer and buffer layout 
        var layout = new[]
        {
            new VertexAttributeDescriptor(VertexAttribute.Position,     VertexAttributeFormat.Float32, 3),
            new VertexAttributeDescriptor(VertexAttribute.Normal,       VertexAttributeFormat.Float32, 3),
            new VertexAttributeDescriptor(VertexAttribute.TexCoord0,    VertexAttributeFormat.Float32, 2)
        };
        mesh.SetVertexBufferParams(vertex_count, layout);

        // init buffer with zeros - not sure if this is necessary
        NativeArray<Vertex> vert_buffer_data = new NativeArray<Vertex>(vertex_count, Allocator.Temp);
        for (int i = 0; i < vertex_count; i++)
        {
            vert_buffer_data[i] = new Vertex(0, 0, 0, 0, 0, 0, 0, 0);
        }
        mesh.SetVertexBufferData(vert_buffer_data, 0, 0, vertex_count);

        // Init indexes that make up the triangles
        int[] tris_array = new int[index_count];
        for (int i = 0; i < index_count; i++)
        {
            tris_array[i] = 0;
        }

        //
        mesh.indexFormat    = UnityEngine.Rendering.IndexFormat.UInt32;
        mesh.triangles      = tris_array;

        // TODO - would be nice to get this way working to be consistent 
        /*      
         mesh.SetIndexBufferParams(index_count, IndexFormat.UInt32);
         NativeArray<int> index_buffer_data = new NativeArray<int>(index_count, Allocator.Temp);
         for (int i = 0; i < index_count; i++)
         {
            index_buffer_data[i] = 0;
         }
         mesh.SetIndexBufferData(index_buffer_data, 0, 0, index_count);

         mesh.subMeshCount = 1;
         mesh.SetSubMesh(0, new SubMeshDescriptor(0, 0, MeshTopology.Triangles));
         */

        // Get Buffer Handles
        IntPtr index_buffer     = mesh.GetNativeIndexBufferPtr();
        IntPtr vertex_buffer    = mesh.GetNativeVertexBufferPtr(0);

        Debug.Log(String.Format("VolumetricVideoDecoder::init_mesh - {0} {1}", index_buffer, vertex_buffer));

        // Pass handles to Native Plugin
        if (volumetricvideo_set_mesh_pointer(m_instance_id, index_buffer, index_count, vertex_buffer, vertex_count ) == -1)
        {
            return false;
        }

        //
        Debug.Log("VolumetricVideoDecoder::init_mesh - Done");
        return true;
    }

    //----------------------------------------------------------
    // Init Mesh data
    //----------------------------------------------------------
    public bool init_mesh_data(string filepattern, int start_index, int stop_index)
    {
   
        if(volumetricvideo_load_mesh_data(m_instance_id, filepattern, start_index, stop_index) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init_mesh_data - Error");
            return false;
        }

        Debug.Log("VolumetricVideoDecoder::init_mesh_data - Done");
        return true;
    }


    //----------------------------------------------------------
    // Start the decoder
    //----------------------------------------------------------
    public bool start_decoding()
    {
        //
        if(volumetricvideo_start_decoding(m_instance_id) == -1)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::start - Failed to start decoder for instance {0}",m_instance_id) );
            return false;
        }

        //
        return true;
    }

    //----------------------------------------------------------
    // Stop the decoder
    //----------------------------------------------------------
    public bool stop_decoding()
    {
        //
        if(volumetricvideo_stop_decoding(m_instance_id) == -1)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::start - Failed to start decoder for instance {0}",m_instance_id) );
            return false;
        }

        //
        return true;
    }


    //----------------------------------------------------------
    // Function to set the frame counter - this should be a time within the volumetric sequence e.g. 5 secs
    // This is then normalised within the sequence
    //----------------------------------------------------------
    public void update(double time)
    {
        // Compute frame within the sequence
        int current_frame = (int)( (time * video_fps) % (video_fps*video_duration) );

        //Check if there is a requirement to update the frame
        if (m_previous_frame != current_frame)
        { 
            // Set frame index to display within native plugin
            volumetricvideo_set_frame(m_instance_id, current_frame);

            // Issue render event
            GL.IssuePluginEvent(GetRenderEventFunc(), m_instance_id);

            // keep track of previous frame
            m_previous_frame = current_frame;
        }    
    }

}
