using System.Collections;
using System.Collections.Generic;

using UnityEngine;
using UnityEngine.Rendering;
using Unity.Collections;

using System.Runtime.InteropServices;
using System;

namespace OpenVol
{

/// <summary>
/// Managed bridge to one native volumetric-video decoder instance.
///
/// Unity owns the Mesh, Material, Texture2D objects, and AudioClip. The native
/// plugin decodes the combined MP4 and writes into registered graphics buffers
/// during GL.IssuePluginEvent. Audio is pulled through the streaming AudioClip
/// callback.
/// </summary>
public class VolumetricVideoDecoder : IDisposable
{
    //---------------------------------------------
    // DLL Interface
    //---------------------------------------------
    const string DLLNAME = "OpenVolUnityPlugin";

    // DLL Interfacece
    [DllImport(DLLNAME, EntryPoint = "GetRenderEventFunc")]
    private static extern IntPtr GetRenderEventFunc();

    [DllImport(DLLNAME, EntryPoint = "openvol_open_external_console")]
    private static extern void openvol_open_external_console();

    [DllImport(DLLNAME, EntryPoint = "openvol_close_external_console")]
    private static extern void openvol_close_external_console();

    [DllImport(DLLNAME, EntryPoint = "openvol_init")]
    private static extern int openvol_init(ref int ID);

    [DllImport(DLLNAME, EntryPoint = "openvol_quit")]
    private static extern void openvol_quit(int ID);

    [DllImport(DLLNAME, EntryPoint = "openvol_set_time")]
    private static extern void openvol_set_time(int ID, double time);

    [DllImport(DLLNAME, EntryPoint = "openvol_start_decoding")]
    private static extern int openvol_start_decoding(int ID);

    [DllImport(DLLNAME, EntryPoint = "openvol_stop_decoding")]
    private static extern int openvol_stop_decoding(int ID);

    [DllImport(DLLNAME, EntryPoint = "openvol_seek")]
    private static extern int openvol_seek(int ID, double time);

    [DllImport(DLLNAME, EntryPoint = "openvol_load_video")]
    private static extern int openvol_load_video(int ID, string filename);

    [DllImport(DLLNAME, EntryPoint = "openvol_get_last_error")]
    private static extern IntPtr openvol_get_last_error(int ID);

    [DllImport(DLLNAME, EntryPoint = "openvol_get_last_presented_time")]
    private static extern double openvol_get_last_presented_time(int ID);

    [DllImport(DLLNAME, EntryPoint = "openvol_get_video_details")]
    private static extern int openvol_get_video_details(int ID, ref int width, ref int height, ref double fps, ref double duration);

    [DllImport(DLLNAME, EntryPoint = "openvol_get_audio_details")]
    private static extern int openvol_get_audio_details(int ID, ref int sample_rate, ref int channels);

    [DllImport(DLLNAME, EntryPoint = "openvol_read_audio")]
    private static extern int openvol_read_audio(int ID, [Out] float[] samples, int sample_count);

    [DllImport(DLLNAME, EntryPoint = "openvol_get_texture_pointers")]
    private static extern int openvol_get_texture_pointers(int ID, ref IntPtr Y, ref IntPtr U, ref IntPtr V);

    [DllImport(DLLNAME, EntryPoint = "openvol_register_texture_pointers")]
    private static extern int openvol_register_texture_pointers(
        int ID, IntPtr Y, IntPtr U, IntPtr V);

    [DllImport(DLLNAME, EntryPoint = "openvol_set_mesh_pointer")]
    private static extern int openvol_set_mesh_pointer(int ID, IntPtr index_buffer_handle, int index_size, IntPtr vertex_buffer_handle, int vertex_size);

    //---------------------------------------------
    // Member variables
    //---------------------------------------------

    // Instance ID generated by plugin
    private int m_instance_id = -1;

    // Width and height of video - returned by plugin
    private int video_width = -1, video_height = -1;

    // Video FPS and duration returned by plugin
    private double video_fps = 0.0, video_duration = 0.0;

    // Textures - resources generated by Plugin and then constructed with unity in init_textures funciton
    private Texture2D m_YTexture, m_UTexture, m_VTexture;

    private AudioClip m_audio_clip;
    public AudioClip AudioClip
    {
        get { return m_audio_clip; }
    }

    public bool HasAudio
    {
        get { return m_audio_clip != null; }
    }

    // Mesh Filter - the form of the object
    private Mesh m_mesh;
    public Mesh Mesh
    {
        get{return m_mesh;}
    }

    // Mesh Renderer - the way the object looks on screen
    private MeshRenderer m_mesh_renderer;
    public MeshRenderer MeshRenderer
    {
        get {return m_mesh_renderer;}
    }


    // keeps track of last frame index that has been displayed
    private int m_previous_frame;

    // Flag for debug mode
    private bool m_debug;
    private bool m_disposed;

    // Enum for decodered state
    public enum DecoderState
    {
        INIT_FAIL = -1,
        UNINITIALIZED,
        INITIALIZED,
        STARTED,
        STOPPED,
    };

    // 
    private DecoderState m_decoder_state = DecoderState.UNINITIALIZED;
    public DecoderState DecoderStatus
    {
        get{return m_decoder_state; }
        set { m_decoder_state = value; }
    }

    // Flag to detect a loop has occured
    private bool m_loop = false;
    public bool ContentLooped
    {
        get { return m_loop; }
    }

    public double Duration
    {
        get { return video_duration; }
    }

    public double FrameRate
    {
        get { return video_fps; }
    }

    public string LastError
    {
        get
        {
            if(m_instance_id < 0)
            {
                return String.Empty;
            }
            IntPtr message = openvol_get_last_error(m_instance_id);
            return message == IntPtr.Zero
                ? String.Empty
                : Marshal.PtrToStringAnsi(message);
        }
    }

    public double LastPresentedTime
    {
        get { return openvol_get_last_presented_time(m_instance_id); }
    }

    //---------------------------------------------
    // Constructor
    //---------------------------------------------
    public VolumetricVideoDecoder(bool debug)
    {
        // Set state to uninitialised 
        m_decoder_state = DecoderState.UNINITIALIZED;

        // Set up debug console
        m_debug = debug;
        if (m_debug)
        {
            Debug.Log("VolumetricVideoDecoder - Opening External Console");
            openvol_open_external_console();
        }

        // Init Instance of Volumetric Video decoder
        if (openvol_init(ref m_instance_id) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init - failed to init");
            m_decoder_state = DecoderState.INIT_FAIL;
        }
        Debug.Log(String.Format("VolumetricVideoDecoder::init - instance ID: {0}", m_instance_id));

        // decoder init
        m_decoder_state = DecoderState.INITIALIZED;
    }

    /// <summary>
    /// Releases native decoder and graphics resources while Unity's graphics
    /// device is still alive. This must be called from the main thread.
    /// </summary>
    public void Dispose()
    {
        if (m_disposed)
        {
            return;
        }
        m_disposed = true;

        // Release Textures
        m_YTexture = null;
        m_UTexture = null;
        m_VTexture = null;
        m_audio_clip = null;
        
        // Close logging terminal
        if(m_debug)
        {
            Debug.Log(String.Format(
                "VolumetricVideoDecoder::Dispose - Closing External Console - id: {0}",
                m_instance_id));
            openvol_close_external_console();
        }

        // quit decoder plugin
        if (m_instance_id >= 0)
        {
            Debug.Log(String.Format(
                "VolumetricVideoDecoder::Dispose - id: {0}",
                m_instance_id));
            openvol_quit(m_instance_id);
            m_instance_id = -1;
        }

        GC.SuppressFinalize(this);
    }


    //----------------------------------------------------------
    // Vertex Data structure
    //----------------------------------------------------------
    [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]
    struct Vertex
    {
        public Vertex(float x, float y, float z, float nx, float ny, float nz, float u, float v)
        {
            pos     = new Vector3(x, y, z);
            normal  = new Vector3(nx, ny, nz);
            uv      = new Vector3(u, v);
        }
        public Vector3 pos;
        public Vector3 normal;
        public Vector2 uv;
    }

    //----------------------------------------------------------
    // Start the decoder
    //----------------------------------------------------------
    public bool init_mesh()
    {
        // Check for init
        if (m_decoder_state != DecoderState.INITIALIZED)
        {
            Debug.LogError("VolumetricVideoDecoder::init_mesh - failed to init");
            return false;
        }

        // Create New Mesh
        m_mesh = new Mesh();

        // Mark mesh as dynamic so it is writable and accessiable on the CPU
        m_mesh.MarkDynamic();

        // Vertex Count 
        const int vertex_count = 65535 ;
        const int index_count = 3 * 100000;

         // allocated vertex buffer and buffer layout 
        var layout = new[]
        {
            new VertexAttributeDescriptor(VertexAttribute.Position,     VertexAttributeFormat.Float32, 3),
            new VertexAttributeDescriptor(VertexAttribute.Normal,       VertexAttributeFormat.Float32, 3),
            new VertexAttributeDescriptor(VertexAttribute.TexCoord0,    VertexAttributeFormat.Float32, 2)
        };
        m_mesh.SetVertexBufferParams(vertex_count, layout);

        // init buffer with zeros - not sure if this is necessary
        NativeArray<Vertex> vert_buffer_data = new NativeArray<Vertex>(vertex_count, Allocator.Temp);
        for (int i = 0; i < vertex_count; i++)
        {
            vert_buffer_data[i] = new Vertex(0, 0, 0, 0, 0, 0, 0, 0);
        }
        m_mesh.SetVertexBufferData(vert_buffer_data, 0, 0, vertex_count);
        vert_buffer_data.Dispose();

        // Init indexes that make up the triangles
        int[] tris_array = new int[index_count];
        for (int i = 0; i < index_count; i++)
        {
            tris_array[i] = 0;
        }

        //
        m_mesh.indexFormat    = UnityEngine.Rendering.IndexFormat.UInt32;
        m_mesh.triangles      = tris_array;

        // Get Buffer Handles
        IntPtr index_buffer     = m_mesh.GetNativeIndexBufferPtr();
        IntPtr vertex_buffer    = m_mesh.GetNativeVertexBufferPtr(0);

        Debug.Log(String.Format("VolumetricVideoDecoder::init_mesh - {0} {1}", index_buffer, vertex_buffer));

        // Pass handles to Native Plugin
        if (openvol_set_mesh_pointer(m_instance_id, index_buffer, index_count, vertex_buffer, vertex_count ) == -1)
        {
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        //
        Debug.Log("VolumetricVideoDecoder::init_mesh - Done");
        return true;
    }


    //---------------------------------------------
    // Function to init the volumetric video decoder
    // Requires a reference to the MeshRenderer from the parent class
    //---------------------------------------------
    public bool init_texture(ref  MeshRenderer mesh_renderer, string video_file)
    {
        //
        m_mesh_renderer = mesh_renderer;

        // Check for init
        if (m_decoder_state != DecoderState.INITIALIZED)
        {
            Debug.LogError("VolumetricVideoDecoder::init_texture - failed to init");
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        // Load Video
        if(!load_video(video_file, ref video_width, ref video_height, ref video_fps, ref video_duration))
        {
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }   

        // Create Texture Resources         
        if(!init_textures(ref  m_mesh_renderer, video_width, video_height))
        {
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }
         
        // Seek to start of file
        openvol_seek(m_instance_id, 0.0);
        
        //
        return true;
    }


    //---------------------------------------------
    // Load video and return important properties
    //---------------------------------------------
    private bool load_video(string filepath,  ref int video_width, ref int video_height, ref double video_fps, ref double video_duration )
    {
        // Load Video
        if (openvol_load_video(m_instance_id, filepath) == -1)
        {
            IntPtr errorPointer = openvol_get_last_error(m_instance_id);
            string detail = errorPointer == IntPtr.Zero
                ? String.Empty
                : Marshal.PtrToStringAnsi(errorPointer);
            Debug.LogError("VolumetricVideoDecoder::init - failed to load video"
                + (String.IsNullOrEmpty(detail) ? String.Empty : ": " + detail));
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        // Get Video Details
        if(openvol_get_video_details(m_instance_id,  ref video_width, ref video_height, ref video_fps, ref video_duration) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init - failed to get video details");
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        // Log some details
        Debug.Log( String.Format("VolumetricVideoDecoder::init - file:  {0}", filepath));
        Debug.Log( String.Format("VolumetricVideoDecoder::init - width: {0}  height:   {1}",video_width, video_height));
        Debug.Log( String.Format("VolumetricVideoDecoder::init - fps:   {0}  duration: {1}",video_fps, video_duration));

        //
        return true;
    }

    public bool init_audio()
    {
        int sampleRate = 0;
        int channels = 0;
        int result = openvol_get_audio_details(
            m_instance_id, ref sampleRate, ref channels);
        if (result == 0)
        {
            Debug.Log("VolumetricVideoDecoder::init_audio - no audio stream");
            return true;
        }
        if (result < 0 || sampleRate <= 0 || channels <= 0)
        {
            Debug.LogError("VolumetricVideoDecoder::init_audio - invalid audio stream");
            return false;
        }

        int lengthSamples = Math.Max(
            1, (int)Math.Ceiling(video_duration * sampleRate));
        m_audio_clip = AudioClip.Create(
            "OpenVolAudio",
            lengthSamples,
            channels,
            sampleRate,
            true,
            read_audio);
        Debug.Log(String.Format(
            "VolumetricVideoDecoder::init_audio - {0} Hz, {1} channels",
            sampleRate, channels));
        return m_audio_clip != null;
    }

    private void read_audio(float[] samples)
    {
        int read = openvol_read_audio(
            m_instance_id, samples, samples.Length);
        if (read < 0)
        {
            Array.Clear(samples, 0, samples.Length);
        }
    }


    //---------------------------------------------
    // Function to create texture pointers which are then created by the native plugin
    //---------------------------------------------
    private bool init_textures(ref  MeshRenderer mesh_renderer, int width, int height)
    {
        // Find shader
        try
        {
            mesh_renderer.material = new Material(Shader.Find("OpenVol/YUV2RGBA"));
        }
        catch
        {
            Debug.LogError("VolumetricVideoDecoder::init_textures - YUV2RGBA shader not found");
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        // Create textures 
        IntPtr Y = new IntPtr();
        IntPtr U = new IntPtr();
        IntPtr V = new IntPtr();
    
        // Get/Set texture pointers
        if(openvol_get_texture_pointers(m_instance_id, ref Y, ref U, ref V) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init_textures - Error Creating Textures");
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }

        // Create Unity Textures - Y is full size - U & V are half size
#if UNITY_ANDROID && !UNITY_EDITOR
        const TextureFormat planeFormat = TextureFormat.R8;
#else
        const TextureFormat planeFormat = TextureFormat.Alpha8;
#endif
        m_YTexture = Texture2D.CreateExternalTexture(width,     height,     planeFormat, false, true, Y);
        m_UTexture = Texture2D.CreateExternalTexture(width/2,   height/2,   planeFormat, false, true, U);
        m_VTexture = Texture2D.CreateExternalTexture(width/2,   height/2,   planeFormat, false, true, V);

#if UNITY_ANDROID && !UNITY_EDITOR
        // Unity tracks Vulkan resource state using its own native handles.
        // Register those handles after wrapping the plugin-owned VkImages.
        if (openvol_register_texture_pointers(
                m_instance_id,
                m_YTexture.GetNativeTexturePtr(),
                m_UTexture.GetNativeTexturePtr(),
                m_VTexture.GetNativeTexturePtr()) == -1)
        {
            Debug.LogError("VolumetricVideoDecoder::init_textures - Error Registering Vulkan Textures");
            m_decoder_state = DecoderState.INIT_FAIL;
            return false;
        }
#endif

        // Set Shader Uniforms
        mesh_renderer.material.SetTexture("_YTex", m_YTexture);
        mesh_renderer.material.SetTexture("_UTex", m_UTexture);
        mesh_renderer.material.SetTexture("_VTex", m_VTexture);

        //
        return true;
    }


    //----------------------------------------------------------
    // Start the decoder
    //----------------------------------------------------------
    public bool start_decoding()
    {
        // Check decoder has started before attempting to stop
        if (m_decoder_state != DecoderState.INITIALIZED)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::start - Failed to start decoder for instance {0} - decoder not initialised", m_instance_id));
            return false;
        }

        // Start Decoder
        if (openvol_start_decoding(m_instance_id) == -1)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::start - Failed to start decoder for instance {0}",m_instance_id) );
            return false;
        }

        // Update internal state
        m_decoder_state = DecoderState.STARTED;

        //
        return true;
    }

    //----------------------------------------------------------
    // Stop the decoder
    //----------------------------------------------------------
    public bool stop_decoding()
    {
        // If decoder has stopped - then nothing to do
        if(m_decoder_state == DecoderState.STOPPED)
        {    
            return false;
        }

        // Check decoder has started before attempting to stop
        if(m_decoder_state != DecoderState.STARTED)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::stop - Failed to stop decoder for instance {0} - Decoder status has not started", m_instance_id));
            return false;
        }

        //
        if(openvol_stop_decoding(m_instance_id) == -1)
        {
            Debug.LogError(String.Format("VolumetricVideoDecoder::stop - Failed to start decoder for instance {0}",m_instance_id) );
            return false;
        }

        //
        m_decoder_state = DecoderState.STOPPED;

        //
        return true;
    }

    public bool seek(double time)
    {
        if (m_decoder_state != DecoderState.STARTED ||
            video_duration <= 0.0)
        {
            return false;
        }

        double target = Math.Max(0.0, Math.Min(time, video_duration));
        if (openvol_seek(m_instance_id, target) == -1)
        {
            Debug.LogError(String.Format(
                "VolumetricVideoDecoder::seek - Failed to seek to {0:F3}",
                target));
            return false;
        }

        m_previous_frame = -1;
        m_loop = false;
        return true;
    }

    public void reset_loop_flag()
    {
        m_loop = false;
    }


    //----------------------------------------------------------
    // Function to set the frame counter - this should be a time within the volumetric sequence e.g. 5 secs
    // This is then normalised within the sequence
    //----------------------------------------------------------
    public void update(double time)
    {
        double presentation_time = time % video_duration;

        // Compute frame within the sequence
        int current_frame = (int)(presentation_time * video_fps);

        // Update frame bookkeeping and loop detection only when the encoded
        // frame changes. The render callback is still issued every Unity
        // update so a texture waiting for asynchronous Draco output can retry
        // the same timestamp instead of being abandoned on the next frame.
        if (m_previous_frame != current_frame)
        {
            // The managed playback clock owns loop detection. Reset every
            // native stream before requesting frame zero so no texture,
            // geometry, or audio from the previous pass can leak across.
            int total_frames = (int)(video_duration * video_fps);
            int loop_guard_frames = System.Math.Max(2, (int)video_fps * 2);
            bool crossed_loop_boundary =
                current_frame < m_previous_frame &&
                m_previous_frame >= total_frames - loop_guard_frames &&
                current_frame <= loop_guard_frames;
            if(crossed_loop_boundary)
            {
                m_loop = true;
                if(openvol_seek(m_instance_id, 0.0) == -1)
                {
                    Debug.LogError("VolumetricVideoDecoder::update - failed to reset decoder at loop boundary");
                    return;
                }
            }

            // keep track of previous frame
            m_previous_frame = current_frame;
        }

        // Video, geometry, and audio all use the same presentation time.
        openvol_set_time(m_instance_id, presentation_time);
        GL.IssuePluginEvent(GetRenderEventFunc(), m_instance_id);
        m_mesh.RecalculateBounds();
    }

    //----------------------------------------------------------
    //
    //----------------------------------------------------------
    public void set_colour_correction_values(float luminaceCorrection, float blueProjectionCorrection, float redProjectionCorrection)
    {
        if(m_decoder_state >= DecoderState.INITIALIZED)
        {
             m_mesh_renderer.material.SetFloat("_LuminanceCorrection", luminaceCorrection);
             m_mesh_renderer.material.SetFloat("_BlueProjectionCorrection", blueProjectionCorrection);
             m_mesh_renderer.material.SetFloat("_RedProjectionCorrection", redProjectionCorrection);
        }
    }


}

}
